//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWinForms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=..\\..\\..\\..\\DB\\ML.AccessControl.db;Pooling=true;FailIfMissing=true")]
        public string SQLiteConnectionString {
            get {
                return ((string)(this["SQLiteConnectionString"]));
            }
            set {
                this["SQLiteConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\SQL2008;Integrated Security=SSPI;Database=ML.AccessControl;" +
            "")]
        public string SQLServerConnectionString {
            get {
                return ((string)(this["SQLServerConnectionString"]));
            }
            set {
                this["SQLServerConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ML.AccessControl.DAL.SQLite.DBFactory, ML.AccessControl.DAL.SQLite")]
        public string SQLiteDALType {
            get {
                return ((string)(this["SQLiteDALType"]));
            }
            set {
                this["SQLiteDALType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ML.AccessControl.DAL.SQLServer.DBFactory, ML.AccessControl.DAL.SQLServer")]
        public string SQLServerDALType {
            get {
                return ((string)(this["SQLServerDALType"]));
            }
            set {
                this["SQLServerDALType"] = value;
            }
        }
    }
}
