//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ML.AccessControl.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ML.AccessControl.Common.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login name.
        /// </summary>
        public static string ERR_1000 {
            get {
                return ResourceManager.GetString("ERR_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login name is too short.
        /// </summary>
        public static string ERR_1001 {
            get {
                return ResourceManager.GetString("ERR_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login name is too long.
        /// </summary>
        public static string ERR_1002 {
            get {
                return ResourceManager.GetString("ERR_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login name is not available.
        /// </summary>
        public static string ERR_1003 {
            get {
                return ResourceManager.GetString("ERR_1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        public static string ERR_1100 {
            get {
                return ResourceManager.GetString("ERR_1100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is too short.
        /// </summary>
        public static string ERR_1101 {
            get {
                return ResourceManager.GetString("ERR_1101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is too long.
        /// </summary>
        public static string ERR_1102 {
            get {
                return ResourceManager.GetString("ERR_1102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not available.
        /// </summary>
        public static string ERR_1103 {
            get {
                return ResourceManager.GetString("ERR_1103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name.
        /// </summary>
        public static string ERR_1200 {
            get {
                return ResourceManager.GetString("ERR_1200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is too short.
        /// </summary>
        public static string ERR_1201 {
            get {
                return ResourceManager.GetString("ERR_1201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is too long.
        /// </summary>
        public static string ERR_1202 {
            get {
                return ResourceManager.GetString("ERR_1202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid first name.
        /// </summary>
        public static string ERR_1220 {
            get {
                return ResourceManager.GetString("ERR_1220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is too short.
        /// </summary>
        public static string ERR_1221 {
            get {
                return ResourceManager.GetString("ERR_1221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is too long.
        /// </summary>
        public static string ERR_1222 {
            get {
                return ResourceManager.GetString("ERR_1222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid last name.
        /// </summary>
        public static string ERR_1240 {
            get {
                return ResourceManager.GetString("ERR_1240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is too short.
        /// </summary>
        public static string ERR_1241 {
            get {
                return ResourceManager.GetString("ERR_1241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is too long.
        /// </summary>
        public static string ERR_1242 {
            get {
                return ResourceManager.GetString("ERR_1242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string ERR_1300 {
            get {
                return ResourceManager.GetString("ERR_1300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too short.
        /// </summary>
        public static string ERR_1301 {
            get {
                return ResourceManager.GetString("ERR_1301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too long.
        /// </summary>
        public static string ERR_1302 {
            get {
                return ResourceManager.GetString("ERR_1302", resourceCulture);
            }
        }
    }
}
